name: automated tests
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, edited]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: installation
        run: npm install --save-dev cypress-cucumber-preprocessor
        
      - name: installation2
        run: npm install
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm test
